<#
.SYNOPSIS
    Builds the shipping release binary with build-machine paths stripped, and
    hard-fails if any machine-identifying path survives into the artifact.

.DESCRIPTION
    Why this script exists (2026-09-07 security audit finding SEC-01):

    rustc records the source path of every dependency file into the binary so
    that `panic!` can report a location (`core::panic::Location::file()`).
    For crates.io dependencies those paths are ABSOLUTE, so a plain
    `cargo build --release` on this project produced 1154 embedded copies of

        <CARGO_HOME>\registry\src\index.crates.io-<hash>\<crate>-<ver>\src\*.rs

    where <CARGO_HOME> is the developer's real profile directory -- i.e. the
    developer's Windows account name, shipped inside a public GitHub release
    asset, and re-emitted into every end-user crash report written by
    src/crash_reporter.rs (which records panic location + backtrace).

    `--remap-path-prefix` rewrites those to a neutral `/cargo-registry` root.
    Crate name, version, file and line are all preserved, so panic diagnostics
    stay exactly as useful for debugging.

    The obvious alternative, Cargo's `[profile.release] trim-paths`, is NOT
    usable here: it is still unstable on this toolchain (cargo 1.98.1 rejects
    the manifest outright with "feature `trim-paths` is required"). Verified,
    not assumed.

    The remap prefix is written to a LOCAL, GIT-IGNORED .cargo/config.toml
    rather than passed as a one-off environment variable, for two reasons:
      1. It must never be committed -- the prefix literally contains the
         developer's home directory.
      2. Applying it via config.toml means `cargo check`, debug builds and
         release builds all agree on RUSTFLAGS, so they share one fingerprint
         and do not invalidate each other's caches. Passing RUSTFLAGS only for
         release builds would force a full ~680-crate rebuild every time you
         switched between `cargo check` and a release build.

.NOTES
    Run from the native-rust directory:  .\build-release.ps1
#>

[CmdletBinding()]
param(
    # Skip the rebuild and only re-run the leak gate against the existing exe.
    [switch]$VerifyOnly
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
Set-Location -LiteralPath $PSScriptRoot

$exePath = Join-Path $PSScriptRoot 'target\release\osw_native.exe'

if (-not $VerifyOnly) {
    # --- Resolve this machine's cargo roots -------------------------------
    $cargoHome = if ($env:CARGO_HOME) { $env:CARGO_HOME } else { Join-Path $env:USERPROFILE '.cargo' }
    $registrySrc = Join-Path $cargoHome 'registry\src'
    $gitCheckouts = Join-Path $cargoHome 'git\checkouts'

    if (-not (Test-Path -LiteralPath $registrySrc)) {
        throw "Cargo registry source root not found at '$registrySrc'. Set CARGO_HOME or run 'cargo fetch' first."
    }

    # --- Write the local, git-ignored cargo config ------------------------
    # Escaped for TOML basic strings: backslashes must be doubled.
    function ConvertTo-TomlPath([string]$p) { $p.Replace('\', '\\') }

    $flags = @(
        "`"--remap-path-prefix=$(ConvertTo-TomlPath $registrySrc)=/cargo-registry`""
        "`"--remap-path-prefix=$(ConvertTo-TomlPath $gitCheckouts)=/cargo-git`""
    ) -join ', '

    $configDir = Join-Path $PSScriptRoot '.cargo'
    $null = New-Item -ItemType Directory -Force -Path $configDir
    $configPath = Join-Path $configDir 'config.toml'

    @"
# GENERATED BY build-release.ps1 -- DO NOT COMMIT.
# This file is git-ignored on purpose: the prefixes below contain this
# machine's home directory. See build-release.ps1 for the full rationale
# (security audit finding SEC-01, 2026-09-07).
[build]
rustflags = [$flags]
"@ | Set-Content -LiteralPath $configPath -Encoding UTF8

    Write-Host "[1/3] Wrote $configPath" -ForegroundColor Cyan
    Write-Host "[2/3] cargo build --release" -ForegroundColor Cyan
    & cargo build --release
    if ($LASTEXITCODE -ne 0) { throw "cargo build --release failed with exit code $LASTEXITCODE" }
}

# --- Egress gate: fail loudly if any build-machine path survived ----------
Write-Host "[3/3] Scanning artifact for machine-identifying paths" -ForegroundColor Cyan

if (-not (Test-Path -LiteralPath $exePath)) { throw "Artifact not found: $exePath" }

$bytes = [System.IO.File]::ReadAllBytes($exePath)
# The embedded path strings are plain ASCII/UTF-8, so a Latin-1 decode is a
# faithful 1-byte-per-char view of the whole image for regex purposes.
$text = [System.Text.Encoding]::GetEncoding('ISO-8859-1').GetString($bytes)

# Any drive-qualified user-profile path is disqualifying, regardless of whose.
$leakPattern = '[A-Za-z]:\\Users\\'
$leaks = [regex]::Matches($text, "$leakPattern[^\s`"<>|]{0,120}")

if ($leaks.Count -gt 0) {
    $samples = ($leaks | Select-Object -First 5 | ForEach-Object { $_.Value } | Sort-Object -Unique) -join "`n    "
    Write-Host ""
    Write-Host "FAIL: $($leaks.Count) build-machine path(s) embedded in $exePath" -ForegroundColor Red
    Write-Host "    $samples" -ForegroundColor Red
    Write-Host ""
    Write-Host "This artifact MUST NOT be published. See build-release.ps1 header." -ForegroundColor Red
    exit 1
}

$remapped = [regex]::Matches($text, '/cargo-registry').Count
Write-Host ""
Write-Host "PASS: 0 build-machine paths embedded ($remapped dependency paths remapped)." -ForegroundColor Green
Write-Host "Artifact: $exePath" -ForegroundColor Green
exit 0
